adds support for svg
yannikstauffer/ffhs-latex-template pull request #1
Opened 2024-03-01 10:44 UTC by Fabian-Wey-FFHS

adds svg versions of ffhs logos
replaces png logo on title with svg logo

2024-03-01 14:26 UTC, yannikstauffer requested changes
Seems like the the commit for actually using the svg in the *.tex-file is missing. Did it not get pushed?

2024-03-02 09:45 UTC, Fabian-Wey-FFHS commented
Exactly. I made a mistake...

2024-03-02 09:48 UTC, Fabian-Wey-FFHS commented
Ich kenne mich leider mit Pull-Requests nicht aus. Siehst du beide commits? im 2. commit habe ich main.tex und die "Title Page" angepasst.

2024-03-02 13:20 UTC, yannikstauffer requested changes
Danke für die Ergänzung!

Bezüglich deiner Frage: Wenn du neue Commits auf deinen Branch pushst, dann wird das im entsprechenden PR übernommen. Unter dem `Conversation` Tab auf dem PR hier, wird dir dann der Commit historisch an der entsprechenden Stelle angezeigt:

![image](https://github.com/yannikstauffer/ffhs-latex-template/assets/71834953/f5433c99-207e-4c8f-8790-b163cc9715df)

Bemerkung am Rande (hier bei dem Repo kein Problem, da keine Konvention definiert ist): Commits werden i.d.R. in Gegenwartsform geschrieben. Anstelle von `added` oder `adds` müsste da eigentlich `add` stehen.

2024-03-02 13:20 UTC, yannikstauffer commented on main.tex
> +\usepackage[inkscapelatex=false]{svg}
Kannst du das mittels `\RequirePackage` (macht im Grunde dasselbe wie `\usepackage`) im  File `ffhs-config.sty` hinterlegen und dort hintendran noch einen Kommentar machen, dass das für das Laden von SVG genutzt wird? Dann sind alle Packages am selben Ort verwaltet.

2024-03-02 13:20 UTC, yannikstauffer commented on FFHS-Paper-00-Title-Page.tex
> +        %\includegraphics[height=3cm]{resources/images/ffhs_logo.png}%
Du kannst die Zeile komplett rauslöschen. Wenn jemand das PNG nutzen will, dann findet er sicher raus, wie das klappt 😉 

BTW: Kommentare musst du nicht extra mit einem `%` abschliessen.

2024-04-20 08:23 UTC, yannikstauffer commented
Wurde im Rahmen weiterer Anpassungen hinzugefügt.

2024-04-20 08:23 UTC, closed without merging